ImageOptim/libimagequant

libimagequant.c
Even though 'acolormap' is declared const and we use "default(none)",
GCC 6.3.0 does not infer "shared" for it; declare it explicitly.
=> Share acolormap in omp parallel for

Makefile, imagequant.pc
Hello.  This PR adds the generation of pkgconfig when building the shared library. This will be very useful for building packages for different distributives.
Thank you.
=> Add pkgconfig generation for shared lib build

kmeans.c, libimagequant.c, mediancut.c, nearest.c, pam.h
I'm aware of msvc branch, however, with minor modifications master could be used for windows builds with MS compiler.
=> Use alloca for variable length arrays when compiling with MS compiler

Makefile
This changes the Makefile so that on macOS the versioned dylib is named `libimagequant.0.dylib` instead of `libimagequant.dylib.0`.
This is required because macOS uses a different naming scheme for shared library versions
than other Unix OSes.
=> Fix position of SOVER in macOS dylib

Makefile
This fixes an oversight from PR #22, which caused the installed library to be renamed from `libimagequant.0.dylib` to `libimagequant.dylib.0` during `make install`.
=> Fix installed dylib name on macOS

.gitignore, Makefile, imagequant.pc.in
* Build static and shared lib for all target
* Install static lib in install target
* Fix shared lib symlink derefercing during install on macOS
* Fix `imagequant.pc` generation for macOS
* Fix duplicate `libdir=` in `imagequant.pc`
* Rename `imagequant.pc` to `imagequant.pc.in`
* Add `imagequant.pc.in` to distfiles
* Add dynamically generated `imagequant.pc` to `.gitignore`
* Install files without execute permissions
* Create install dirs using `install -d` instead of `mkdir -p`
* Update `install_name` for dylib to allow linking with custom prefix
I've tested the changes on macOS 10.13.4 / Xcode 9.3 and Debian Wheezy using Docker.
=> Tweak Makefile

kmeans.c, libimagequant.c, mediancut.c
OpenMP 4.0 dropped the data-sharing rule that predetermined const-vars
as "shared".  GCC implemented this rule change with GCC-9.  Because of
the rule change, libimagequant fails to build with gcc-9.1.0.  This
patch updates the code so that it is conformant with OpenMP 4.0 rules.
=> Update openmp const-var handling

libimagequant.c
Hello! I'm currently developing Python bindings for LIQ (which is a fantastic piece of software, by the way!), and I noticed this bug while creating some unit tests. Currently, you can set invalid dithering levels because liq_set_dithering_level() checks the wrong variable against the minimum and maximum values. (Tested with version 2.12.3, but the same bug is still present in the master branch.) This PR fixes it.
=> Fix bounds check for setting dithering level

pam.c
This is needed to avoid uninitialized usage later on, which is reported by valgrind as shown below.
It seemed like the best place to put it, but I would just like to make sure. Thanks!
==11283== Conditional jump or move depends on uninitialised value(s)
==11283==    at 0x13D99C: pngquant_quantize (libimagequant.c:2000)
==11283==    by 0x1384B8: liq_histogram_quantize_internal (libimagequant.c:1018)
==11283==    by 0x138334: liq_image_quantize (libimagequant.c:992)
==11283==    by 0x138249: liq_quantize_image (libimagequant.c:970)
==11283==    by 0x12679B: image_quantize (image.c:486)
==11283==    by 0x126BA8: main (main.c:92)
==11283== 
==11283== Use of uninitialised value of size 8
==11283==    at 0x141A9B: nearest_search (nearest.c:174)
==11283==    by 0x1355C6: kmeans_do_iteration …
=> initialize likely_colormap_index

Makefile
Adds the "-lm" link flag to properly compile without the "undefined reference to `powf'" error.
=> Adds proper link flag to the example recipe

rust-api/src/lib.rs
Currently, under the Rust bindings, using the remapped or palette methods allocate `Vec`s to hold the desired data. However, in certain use cases, these extra allocations are unnecessary and may introduce undesirable overhead.
Fix that situation by allowing the caller to provide buffers that will be populated by this crate, and allowing getting slices of palette data, in order to allow avoiding most allocations involved.
=> Flexibilize QuantizationResult API to allow different memory sources

pam.h
The SSE implementation of the function uses single-precision float, whereas this one goes for.... double all over the place.
Extremely unscientific comparisons on godbolt (https://gcc.godbolt.org/z/oa3hP5ffs) shows that both Clang and GCC do much better generating x64 code when float is used. Other SIMD systems should act similarly, but I can't remember the target names. (For more human-like code in clang, try `-Ofast`. I could add an attribute or some assumes there, but ehhhh... sounds unnecessary.)
PS: It might be a good idea to review other internal uses of `double` too. The two cases left appear to be generally sums and other statistics, which I guess is better with `double`, and `gamma`, which has an external `double` API.
=> colordifference_stdc: use float as in SSE

Makefile
I've been carrying this patch downstream for Fedora for while - rpmlint warns if shared libraries are not executable, and such libraries are not picked up by automatic debuginfo exctraction.
=> Install library with execute permission

Cargo.toml
Fixes #68
It produces
```
|- usr/
|- local/
|- include/
|- imagequant/
|- libimagequant.h
|- lib/
|- pkgconfig/
|- imagequant.pc
|- libimagequant.a
|- libimagequant.{dylib/so}
|- libimagequant.4.{dylib/so}
|- libimagequant.4.0.0.{dylib/so}
```
On unix-like and
```
|- usr/
|- local/
|- bin/
|- imagequant.dll
|- include/
|- imagequant/
|- libimagequant.h
|- lib/
|- pkgconfig/
|- imagequant.pc
|- imagequant.def
|- imagequant.dll.a
|- libimagequant.a
``` 
On windows.
=> Add the cargo-c metadata

src/hist.rs
I found this bug when investigating use cases for the lint proposed https://github.com/rust-lang/rust-clippy/pull/8289#issuecomment-1013914592
If a union doesn't have a `#[repr(C)]` attribute on it, the two variants do *not* have to be laid out both starting at offset 0. It would be perfectly valid to treat that `union` keyword as a `struct` keyword, and then suddenly you're reading uninit data / getting the wrong results.
Source for this: https://doc.rust-lang.org/reference/types/union.html says
> The memory layout of a union is undefined by default, but the `#[repr(...)]` attribute can be used to fix a layout.
=> Add repr(C) to unions to ensure variants are laid out at the start

src/remap.rs
The aforementioned commit introduced some plumbing to allow quantizing to more than 256 colors. However, the guard checks it added to error out if an image is remapped to more than 256 colors incorrectly error out when remapping to exactly 256 colors, as u8::MAX == 255 and 256 > 255.
Fix that by comparing against u8::MAX + 1 instead.
=> Fix off by one error in checks introduced in "Allow >256 colors eventually"

README.md, imagequant-sys/README.md
I presume these don't need to be there.
=> Removed references to 4.0.0 beta

src/pal.rs
When using imagequant on 32 bit env I had this bug: 
crossbeam expects pointers (data) to be aligned on 16 bits (because of this repr(C, align(16))) but on 32 bits arch, we can have pointers (data) aligned on 8 bits
=> fix: 32 bits architecture crash

src/rows.rs
fixes 'warning: elided lifetime has a name'
=> fix warning: elided lifetime

imagequant-sys/libimagequant.h, imagequant-sys/src/ffi.rs
Exposing this function through the C interface is more convenient than re-writing `QuantizationResult::from_palette` in C and would provide a clear way for re-using a palette between program runs for new users of the C interface (if documented).
I did not get the Java wrapper to compile and I am not familiar with C#, so I did not touch those interfaces.
=> Add `liq_result_from_palette` to the C interface
